apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-agent-chart.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    # Prometheus Agent configuration
    remote_write:
      - url: {{ .Values.remoteWrite.url | quote }}
        {{- if .Values.remoteWrite.bearerToken.enabled }}
        # Use bearer_token_file to read the token from a mounted secret
        bearer_token_file: /etc/prometheus/secrets/{{ .Values.remoteWrite.bearerToken.secretKey | default "token" }}
        {{- end }}
        {{- if .Values.remoteWrite.basicAuth.enabled }}
        basic_auth:
          username: {{ .Values.remoteWrite.basicAuth.username }}
          password_file: /etc/prometheus/secrets/basic-auth/{{ .Values.remoteWrite.basicAuth.passwordSecretKey }}
        {{- end }}
        {{- if .Values.remoteWrite.tls.enabled }}
        tls_config:
          ca_file: /etc/prometheus/secrets/tls-certs/{{ .Values.remoteWrite.tls.caCertSecretKey }}
          {{- if .Values.remoteWrite.tls.insecure_skip_verify }}
          insecure_skip_verify: true
          {{- else }}
          insecure_skip_verify: false
          {{- end }}
        {{- end }}
        write_relabel_configs:
          - source_labels: [__name__]
            regex: 'action_.*|.*_persistent_volume_.*|repository_data_.*|data_operation_.*|data_upload_session_.*|exec_.*|limiter_.*|export_storage_.*|snapshot_storage_.*|metering_license_.*|events_service_.*|process_.*|compliance_count'
            action: keep
          - source_labels: [__address__]
            regex: '(.*)'
            target_label: cluster
            replacement: {{ .Values.clusterName | quote }}
    scrape_configs:
      - job_name: httpServiceDiscovery
        http_sd_configs:
          - url: http://metering-svc.{{ .Values.kasten.namespace }}.svc.cluster.local:8000/v0/listScrapeTargets
      - job_name: k10-pods
        scheme: http
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              own_namespace: true
            selectors:
              - role: pod
                label: "component=executor"
