apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prometheus-agent-chart.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-agent-chart.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus-agent-chart.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "prometheus-agent-chart.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io