apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-agent-chart.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-agent-chart.labels" . | nindent 4 }}